Practical works
Programming-Classrooms/practicalworks-RostislavStarikov pull request #17
Opened 2024-02-21 19:01 UTC by RostislavStarikov

2024-05-24 06:18 UTC, AnnaSatolina requested changes
надо доделать нормально...чтобы не было разброса методов. И учесть замечания.

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +}
Проверка самоприсваивания?

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +}
у класса стринг есть прекрасный метод size() или length()

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +}
неправильная концепция. Этот метод не должен ничего менять, он должен вернуть что-то новое...а так нет отличий между = и +=

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +}
операторы сравнения дб реализованы по возможности в одну строку. И нет сравнения строк по содержимому.

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +
в одну строку

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +		if (strlen(arr.str) <= strlen(str))
зачем перегружать все операторы сравнения, если достаточно было только двух. А далее, если очень хочется, через вызов этих двух реализовать всё остальное

2024-05-24 06:18 UTC, AnnaSatolina commented on practical-works/myString/src/myString/myString.cpp
> +}
я бы ещё в указатель на строку клала nullptr

2024-05-25 15:37 UTC, AlexandrOsiptsov requested changes
Лишние файлы, проверь .gitignore

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged