Лабораторная работа №2
Programming-Classrooms/practicalworks-RostislavStarikov pull request #19
Opened 2024-04-03 19:56 UTC by RostislavStarikov

Создать многомодульное приложение. Написать класс MyString с базовым
подмножеством операций: конструкторы (по умолчанию, копирования, с
параметрами, перемещения), геттеры, сеттеры, деструктор, перегрузить
операторы =, +, +=, <<, >>.

2024-05-24 06:26 UTC, AnnaSatolina requested changes
посмотри замечания ещё и в лабе майстринг. А вообще ненужное надо удалять, чтобы я по два раза не проверяла.

2024-05-24 06:26 UTC, AnnaSatolina commented on laboratory-task-12/src/myString/myString.cpp
> +
лучше было бы передавать строку в качестве параметра для геттера

2024-05-24 06:26 UTC, AnnaSatolina commented on laboratory-task-12/src/myString/myString.cpp
> +
смотри проверенную лабу майстринг

2024-05-24 06:26 UTC, AnnaSatolina commented on laboratory-task-12/src/myString/myString.hpp
> +
почему друг? вызываться должен объект.метод...аналог же есть в стринг

2024-06-17 16:21 UTC, AlexandrOsiptsov approved these changes
Финальный авто-апрув

2024-06-17 16:42 UTC, merged